# Generated by Django 6.0 on 2025-12-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='link',
            new_name='url',
        ),
    ]
